// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tickets.proto

package tickets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PrintJob struct {
	Filename             string    `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Contest              *IdName   `protobuf:"bytes,2,opt,name=contest,proto3" json:"contest,omitempty"`
	Team                 *IdName   `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	Computer             *Computer `protobuf:"bytes,4,opt,name=computer,proto3" json:"computer,omitempty"`
	Area                 *IdName   `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Data                 []byte    `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp            uint64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Printer              string    `protobuf:"bytes,8,opt,name=printer,proto3" json:"printer,omitempty"`
	JobId                uint32    `protobuf:"varint,9,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Charset              string    `protobuf:"bytes,10,opt,name=charset,proto3" json:"charset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PrintJob) Reset()         { *m = PrintJob{} }
func (m *PrintJob) String() string { return proto.CompactTextString(m) }
func (*PrintJob) ProtoMessage()    {}
func (*PrintJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{0}
}
func (m *PrintJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PrintJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PrintJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *PrintJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintJob.Merge(dst, src)
}
func (m *PrintJob) XXX_Size() int {
	return m.Size()
}
func (m *PrintJob) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintJob.DiscardUnknown(m)
}

var xxx_messageInfo_PrintJob proto.InternalMessageInfo

func (m *PrintJob) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *PrintJob) GetContest() *IdName {
	if m != nil {
		return m.Contest
	}
	return nil
}

func (m *PrintJob) GetTeam() *IdName {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *PrintJob) GetComputer() *Computer {
	if m != nil {
		return m.Computer
	}
	return nil
}

func (m *PrintJob) GetArea() *IdName {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *PrintJob) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PrintJob) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PrintJob) GetPrinter() string {
	if m != nil {
		return m.Printer
	}
	return ""
}

func (m *PrintJob) GetJobId() uint32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *PrintJob) GetCharset() string {
	if m != nil {
		return m.Charset
	}
	return ""
}

type BinaryJob struct {
	Printer              string   `protobuf:"bytes,1,opt,name=printer,proto3" json:"printer,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinaryJob) Reset()         { *m = BinaryJob{} }
func (m *BinaryJob) String() string { return proto.CompactTextString(m) }
func (*BinaryJob) ProtoMessage()    {}
func (*BinaryJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{1}
}
func (m *BinaryJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BinaryJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BinaryJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *BinaryJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryJob.Merge(dst, src)
}
func (m *BinaryJob) XXX_Size() int {
	return m.Size()
}
func (m *BinaryJob) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryJob.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryJob proto.InternalMessageInfo

func (m *BinaryJob) GetPrinter() string {
	if m != nil {
		return m.Printer
	}
	return ""
}

func (m *BinaryJob) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BinaryJob) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type IdName struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdName) Reset()         { *m = IdName{} }
func (m *IdName) String() string { return proto.CompactTextString(m) }
func (*IdName) ProtoMessage()    {}
func (*IdName) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{2}
}
func (m *IdName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IdName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IdName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *IdName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdName.Merge(dst, src)
}
func (m *IdName) XXX_Size() int {
	return m.Size()
}
func (m *IdName) XXX_DiscardUnknown() {
	xxx_messageInfo_IdName.DiscardUnknown(m)
}

var xxx_messageInfo_IdName proto.InternalMessageInfo

func (m *IdName) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Computer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Computer) Reset()         { *m = Computer{} }
func (m *Computer) String() string { return proto.CompactTextString(m) }
func (*Computer) ProtoMessage()    {}
func (*Computer) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{3}
}
func (m *Computer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Computer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Computer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Computer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Computer.Merge(dst, src)
}
func (m *Computer) XXX_Size() int {
	return m.Size()
}
func (m *Computer) XXX_DiscardUnknown() {
	xxx_messageInfo_Computer.DiscardUnknown(m)
}

var xxx_messageInfo_Computer proto.InternalMessageInfo

func (m *Computer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Computer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Ticket struct {
	Contest              *IdName          `protobuf:"bytes,1,opt,name=contest,proto3" json:"contest,omitempty"`
	Team                 *IdName          `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Area                 *IdName          `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"`
	Computer             *Computer        `protobuf:"bytes,4,opt,name=computer,proto3" json:"computer,omitempty"`
	Problem              *Ticket_Problem  `protobuf:"bytes,5,opt,name=problem,proto3" json:"problem,omitempty"`
	SubmitId             uint32           `protobuf:"varint,6,opt,name=submit_id,json=submitId,proto3" json:"submit_id,omitempty"`
	JudgeTime            uint64           `protobuf:"varint,7,opt,name=judge_time,json=judgeTime,proto3" json:"judge_time,omitempty"`
	Submit               []*Ticket_Submit `protobuf:"bytes,8,rep,name=submit,proto3" json:"submit,omitempty"`
	Printer              string           `protobuf:"bytes,9,opt,name=printer,proto3" json:"printer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{4}
}
func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(dst, src)
}
func (m *Ticket) XXX_Size() int {
	return m.Size()
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetContest() *IdName {
	if m != nil {
		return m.Contest
	}
	return nil
}

func (m *Ticket) GetTeam() *IdName {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *Ticket) GetArea() *IdName {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *Ticket) GetComputer() *Computer {
	if m != nil {
		return m.Computer
	}
	return nil
}

func (m *Ticket) GetProblem() *Ticket_Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

func (m *Ticket) GetSubmitId() uint32 {
	if m != nil {
		return m.SubmitId
	}
	return 0
}

func (m *Ticket) GetJudgeTime() uint64 {
	if m != nil {
		return m.JudgeTime
	}
	return 0
}

func (m *Ticket) GetSubmit() []*Ticket_Submit {
	if m != nil {
		return m.Submit
	}
	return nil
}

func (m *Ticket) GetPrinter() string {
	if m != nil {
		return m.Printer
	}
	return ""
}

type Ticket_Submit struct {
	SubmitNumber         uint32                `protobuf:"varint,1,opt,name=submit_number,json=submitNumber,proto3" json:"submit_number,omitempty"`
	Arrived              uint64                `protobuf:"varint,2,opt,name=arrived,proto3" json:"arrived,omitempty"`
	Compiled             bool                  `protobuf:"varint,3,opt,name=compiled,proto3" json:"compiled,omitempty"`
	School               *Ticket_Submit_School `protobuf:"bytes,4,opt,name=school,proto3" json:"school,omitempty"`
	Acm                  *Ticket_Submit_ACM    `protobuf:"bytes,5,opt,name=acm,proto3" json:"acm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Ticket_Submit) Reset()         { *m = Ticket_Submit{} }
func (m *Ticket_Submit) String() string { return proto.CompactTextString(m) }
func (*Ticket_Submit) ProtoMessage()    {}
func (*Ticket_Submit) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{4, 0}
}
func (m *Ticket_Submit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ticket_Submit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ticket_Submit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Ticket_Submit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket_Submit.Merge(dst, src)
}
func (m *Ticket_Submit) XXX_Size() int {
	return m.Size()
}
func (m *Ticket_Submit) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket_Submit.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket_Submit proto.InternalMessageInfo

func (m *Ticket_Submit) GetSubmitNumber() uint32 {
	if m != nil {
		return m.SubmitNumber
	}
	return 0
}

func (m *Ticket_Submit) GetArrived() uint64 {
	if m != nil {
		return m.Arrived
	}
	return 0
}

func (m *Ticket_Submit) GetCompiled() bool {
	if m != nil {
		return m.Compiled
	}
	return false
}

func (m *Ticket_Submit) GetSchool() *Ticket_Submit_School {
	if m != nil {
		return m.School
	}
	return nil
}

func (m *Ticket_Submit) GetAcm() *Ticket_Submit_ACM {
	if m != nil {
		return m.Acm
	}
	return nil
}

type Ticket_Submit_School struct {
	TestsTaken           uint32   `protobuf:"varint,1,opt,name=tests_taken,json=testsTaken,proto3" json:"tests_taken,omitempty"`
	TestsPassed          uint32   `protobuf:"varint,2,opt,name=tests_passed,json=testsPassed,proto3" json:"tests_passed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket_Submit_School) Reset()         { *m = Ticket_Submit_School{} }
func (m *Ticket_Submit_School) String() string { return proto.CompactTextString(m) }
func (*Ticket_Submit_School) ProtoMessage()    {}
func (*Ticket_Submit_School) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{4, 0, 0}
}
func (m *Ticket_Submit_School) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ticket_Submit_School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ticket_Submit_School.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Ticket_Submit_School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket_Submit_School.Merge(dst, src)
}
func (m *Ticket_Submit_School) XXX_Size() int {
	return m.Size()
}
func (m *Ticket_Submit_School) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket_Submit_School.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket_Submit_School proto.InternalMessageInfo

func (m *Ticket_Submit_School) GetTestsTaken() uint32 {
	if m != nil {
		return m.TestsTaken
	}
	return 0
}

func (m *Ticket_Submit_School) GetTestsPassed() uint32 {
	if m != nil {
		return m.TestsPassed
	}
	return 0
}

type Ticket_Submit_ACM struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	TestId               uint32   `protobuf:"varint,2,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket_Submit_ACM) Reset()         { *m = Ticket_Submit_ACM{} }
func (m *Ticket_Submit_ACM) String() string { return proto.CompactTextString(m) }
func (*Ticket_Submit_ACM) ProtoMessage()    {}
func (*Ticket_Submit_ACM) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{4, 0, 1}
}
func (m *Ticket_Submit_ACM) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ticket_Submit_ACM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ticket_Submit_ACM.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Ticket_Submit_ACM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket_Submit_ACM.Merge(dst, src)
}
func (m *Ticket_Submit_ACM) XXX_Size() int {
	return m.Size()
}
func (m *Ticket_Submit_ACM) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket_Submit_ACM.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket_Submit_ACM proto.InternalMessageInfo

func (m *Ticket_Submit_ACM) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Ticket_Submit_ACM) GetTestId() uint32 {
	if m != nil {
		return m.TestId
	}
	return 0
}

type Ticket_Problem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket_Problem) Reset()         { *m = Ticket_Problem{} }
func (m *Ticket_Problem) String() string { return proto.CompactTextString(m) }
func (*Ticket_Problem) ProtoMessage()    {}
func (*Ticket_Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_tickets_cf0ffa94fc4e9142, []int{4, 1}
}
func (m *Ticket_Problem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ticket_Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ticket_Problem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Ticket_Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket_Problem.Merge(dst, src)
}
func (m *Ticket_Problem) XXX_Size() int {
	return m.Size()
}
func (m *Ticket_Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket_Problem proto.InternalMessageInfo

func (m *Ticket_Problem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ticket_Problem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PrintJob)(nil), "tickets.PrintJob")
	proto.RegisterType((*BinaryJob)(nil), "tickets.BinaryJob")
	proto.RegisterType((*IdName)(nil), "tickets.IdName")
	proto.RegisterType((*Computer)(nil), "tickets.Computer")
	proto.RegisterType((*Ticket)(nil), "tickets.Ticket")
	proto.RegisterType((*Ticket_Submit)(nil), "tickets.Ticket.Submit")
	proto.RegisterType((*Ticket_Submit_School)(nil), "tickets.Ticket.Submit.School")
	proto.RegisterType((*Ticket_Submit_ACM)(nil), "tickets.Ticket.Submit.ACM")
	proto.RegisterType((*Ticket_Problem)(nil), "tickets.Ticket.Problem")
}
func (m *PrintJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PrintJob) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Filename) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Filename)))
		i += copy(dAtA[i:], m.Filename)
	}
	if m.Contest != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Contest.Size()))
		n1, err := m.Contest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Team != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Team.Size()))
		n2, err := m.Team.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Computer != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Computer.Size()))
		n3, err := m.Computer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Area != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Area.Size()))
		n4, err := m.Area.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if m.Timestamp != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Timestamp))
	}
	if len(m.Printer) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Printer)))
		i += copy(dAtA[i:], m.Printer)
	}
	if m.JobId != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.JobId))
	}
	if len(m.Charset) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Charset)))
		i += copy(dAtA[i:], m.Charset)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *BinaryJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BinaryJob) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Printer) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Printer)))
		i += copy(dAtA[i:], m.Printer)
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if len(m.JobId) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.JobId)))
		i += copy(dAtA[i:], m.JobId)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *IdName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IdName) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Id))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Computer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Computer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Ticket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ticket) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Contest != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Contest.Size()))
		n5, err := m.Contest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.Team != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Team.Size()))
		n6, err := m.Team.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.Area != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Area.Size()))
		n7, err := m.Area.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	if m.Computer != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Computer.Size()))
		n8, err := m.Computer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if m.Problem != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Problem.Size()))
		n9, err := m.Problem.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	if m.SubmitId != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.SubmitId))
	}
	if m.JudgeTime != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.JudgeTime))
	}
	if len(m.Submit) > 0 {
		for _, msg := range m.Submit {
			dAtA[i] = 0x42
			i++
			i = encodeVarintTickets(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Printer) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Printer)))
		i += copy(dAtA[i:], m.Printer)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Ticket_Submit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ticket_Submit) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SubmitNumber != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.SubmitNumber))
	}
	if m.Arrived != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Arrived))
	}
	if m.Compiled {
		dAtA[i] = 0x18
		i++
		if m.Compiled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.School != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.School.Size()))
		n10, err := m.School.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	if m.Acm != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.Acm.Size()))
		n11, err := m.Acm.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Ticket_Submit_School) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ticket_Submit_School) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TestsTaken != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.TestsTaken))
	}
	if m.TestsPassed != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.TestsPassed))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Ticket_Submit_ACM) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ticket_Submit_ACM) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Result)))
		i += copy(dAtA[i:], m.Result)
	}
	if m.TestId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTickets(dAtA, i, uint64(m.TestId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Ticket_Problem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ticket_Problem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTickets(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintTickets(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *PrintJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Filename)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Contest != nil {
		l = m.Contest.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Team != nil {
		l = m.Team.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Computer != nil {
		l = m.Computer.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Area != nil {
		l = m.Area.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTickets(uint64(m.Timestamp))
	}
	l = len(m.Printer)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.JobId != 0 {
		n += 1 + sovTickets(uint64(m.JobId))
	}
	l = len(m.Charset)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BinaryJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Printer)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *IdName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTickets(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Computer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Ticket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Contest != nil {
		l = m.Contest.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Team != nil {
		l = m.Team.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Area != nil {
		l = m.Area.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Computer != nil {
		l = m.Computer.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Problem != nil {
		l = m.Problem.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.SubmitId != 0 {
		n += 1 + sovTickets(uint64(m.SubmitId))
	}
	if m.JudgeTime != 0 {
		n += 1 + sovTickets(uint64(m.JudgeTime))
	}
	if len(m.Submit) > 0 {
		for _, e := range m.Submit {
			l = e.Size()
			n += 1 + l + sovTickets(uint64(l))
		}
	}
	l = len(m.Printer)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Ticket_Submit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubmitNumber != 0 {
		n += 1 + sovTickets(uint64(m.SubmitNumber))
	}
	if m.Arrived != 0 {
		n += 1 + sovTickets(uint64(m.Arrived))
	}
	if m.Compiled {
		n += 2
	}
	if m.School != nil {
		l = m.School.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.Acm != nil {
		l = m.Acm.Size()
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Ticket_Submit_School) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TestsTaken != 0 {
		n += 1 + sovTickets(uint64(m.TestsTaken))
	}
	if m.TestsPassed != 0 {
		n += 1 + sovTickets(uint64(m.TestsPassed))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Ticket_Submit_ACM) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.TestId != 0 {
		n += 1 + sovTickets(uint64(m.TestId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Ticket_Problem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTickets(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTickets(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTickets(x uint64) (n int) {
	return sovTickets(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PrintJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PrintJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PrintJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filename = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Contest == nil {
				m.Contest = &IdName{}
			}
			if err := m.Contest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Team == nil {
				m.Team = &IdName{}
			}
			if err := m.Team.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Computer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Computer == nil {
				m.Computer = &Computer{}
			}
			if err := m.Computer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Area", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Area == nil {
				m.Area = &IdName{}
			}
			if err := m.Area.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Printer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Printer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Charset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Charset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BinaryJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BinaryJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BinaryJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Printer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Printer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IdName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IdName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IdName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Computer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Computer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Computer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ticket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ticket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ticket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Contest == nil {
				m.Contest = &IdName{}
			}
			if err := m.Contest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Team == nil {
				m.Team = &IdName{}
			}
			if err := m.Team.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Area", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Area == nil {
				m.Area = &IdName{}
			}
			if err := m.Area.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Computer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Computer == nil {
				m.Computer = &Computer{}
			}
			if err := m.Computer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Problem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Problem == nil {
				m.Problem = &Ticket_Problem{}
			}
			if err := m.Problem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitId", wireType)
			}
			m.SubmitId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmitId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeTime", wireType)
			}
			m.JudgeTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JudgeTime |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submit = append(m.Submit, &Ticket_Submit{})
			if err := m.Submit[len(m.Submit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Printer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Printer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ticket_Submit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Submit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Submit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitNumber", wireType)
			}
			m.SubmitNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmitNumber |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arrived", wireType)
			}
			m.Arrived = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Arrived |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Compiled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Compiled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field School", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.School == nil {
				m.School = &Ticket_Submit_School{}
			}
			if err := m.School.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Acm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Acm == nil {
				m.Acm = &Ticket_Submit_ACM{}
			}
			if err := m.Acm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ticket_Submit_School) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: School: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: School: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestsTaken", wireType)
			}
			m.TestsTaken = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TestsTaken |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestsPassed", wireType)
			}
			m.TestsPassed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TestsPassed |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ticket_Submit_ACM) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ACM: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ACM: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestId", wireType)
			}
			m.TestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TestId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ticket_Problem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Problem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Problem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTickets
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTickets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTickets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTickets(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTickets
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTickets
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTickets
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTickets
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTickets(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTickets = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTickets   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("tickets.proto", fileDescriptor_tickets_cf0ffa94fc4e9142) }

var fileDescriptor_tickets_cf0ffa94fc4e9142 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0xb6, 0xed, 0x32, 0x6d, 0x0f, 0xd4, 0x9f, 0x49, 0x84, 0x49, 0x95, 0xb5, 0x2e, 0x37, 0x35,
	0x81, 0x26, 0x62, 0xf4, 0x1e, 0xb8, 0x5a, 0x23, 0x64, 0x33, 0x70, 0x4f, 0xa6, 0xed, 0x28, 0x03,
	0xdb, 0x76, 0xd3, 0xce, 0x9a, 0xf8, 0x26, 0xbe, 0x91, 0x5e, 0x19, 0x1f, 0xc1, 0x60, 0x7c, 0x0f,
	0x33, 0x3f, 0x5d, 0x16, 0x03, 0x04, 0xef, 0x7a, 0xce, 0xf9, 0xce, 0x99, 0x73, 0xbe, 0xef, 0xdb,
	0x85, 0x48, 0x8a, 0xe2, 0x82, 0xcb, 0x2e, 0x9b, 0xb5, 0x8d, 0x6c, 0xb0, 0x6f, 0xc3, 0xd1, 0x37,
	0x17, 0x82, 0x49, 0x2b, 0x6a, 0xf9, 0xbe, 0xc9, 0x71, 0x0c, 0xc1, 0x47, 0x31, 0xe5, 0x35, 0xab,
	0x38, 0x71, 0x12, 0x27, 0x0d, 0xe9, 0x22, 0xc6, 0xaf, 0xc0, 0x2f, 0x9a, 0x5a, 0xf2, 0x4e, 0x12,
	0x37, 0x71, 0xd2, 0xd5, 0xdd, 0x47, 0x59, 0x3f, 0x72, 0x5c, 0x1e, 0xb1, 0x8a, 0xd3, 0xbe, 0x8e,
	0xb7, 0x60, 0x20, 0x39, 0xab, 0x88, 0x77, 0x33, 0x4e, 0x17, 0xf1, 0x0e, 0x04, 0x45, 0x53, 0xcd,
	0xe6, 0x92, 0xb7, 0x64, 0xa0, 0x81, 0x4f, 0x16, 0xc0, 0x03, 0x5b, 0xa0, 0x0b, 0x88, 0x9a, 0xc9,
	0x5a, 0xce, 0xc8, 0xca, 0x2d, 0x33, 0x55, 0x11, 0x63, 0x18, 0x94, 0x4c, 0x32, 0x82, 0x12, 0x27,
	0x5d, 0xa3, 0xfa, 0x1b, 0x3f, 0x87, 0x50, 0x8a, 0x8a, 0x77, 0x92, 0x55, 0x33, 0xe2, 0x27, 0x4e,
	0x3a, 0xa0, 0x57, 0x09, 0x4c, 0xc0, 0x9f, 0xa9, 0xeb, 0x79, 0x4b, 0x02, 0x7d, 0x70, 0x1f, 0xe2,
	0xa7, 0x80, 0xce, 0x9b, 0xfc, 0x54, 0x94, 0x24, 0x4c, 0x9c, 0x34, 0xa2, 0x2b, 0xe7, 0x4d, 0x3e,
	0x2e, 0x55, 0x43, 0x71, 0xc6, 0xda, 0x8e, 0x4b, 0x02, 0xa6, 0xc1, 0x86, 0xa3, 0x09, 0x84, 0xfb,
	0xa2, 0x66, 0xed, 0x17, 0xc5, 0xe4, 0xd2, 0x5c, 0xe7, 0xfa, 0xdc, 0x7e, 0x47, 0x77, 0x69, 0xc7,
	0xab, 0xb7, 0x3c, 0x0d, 0x36, 0x6f, 0x8d, 0xb6, 0x01, 0x99, 0xf3, 0xf0, 0x43, 0x70, 0x45, 0xa9,
	0x27, 0x45, 0xd4, 0x15, 0xa5, 0x1a, 0xa2, 0x45, 0x72, 0x35, 0x5c, 0x7f, 0x8f, 0x32, 0x08, 0x7a,
	0xde, 0x96, 0xf0, 0xe1, 0xad, 0xf8, 0x3f, 0x2b, 0x80, 0x4e, 0x34, 0x8b, 0xcb, 0xda, 0x3a, 0xf7,
	0xd4, 0xd6, 0xbd, 0x4b, 0xdb, 0x5e, 0x2c, 0xef, 0x2e, 0xb1, 0xfe, 0xd3, 0x00, 0xaf, 0x15, 0xa3,
	0x4d, 0x3e, 0xe5, 0x95, 0xf5, 0xc0, 0xc6, 0x02, 0x6d, 0xae, 0xc8, 0x26, 0xa6, 0x4c, 0x7b, 0x1c,
	0x7e, 0x06, 0x61, 0x37, 0xcf, 0x2b, 0x21, 0x15, 0xb3, 0x48, 0x93, 0x17, 0x98, 0xc4, 0xb8, 0xc4,
	0x9b, 0x00, 0xe7, 0xf3, 0xf2, 0x13, 0x3f, 0x55, 0x66, 0xe8, 0x8d, 0xa1, 0x33, 0x27, 0xa2, 0xe2,
	0x38, 0x03, 0x64, 0xa0, 0x24, 0x48, 0xbc, 0x74, 0x75, 0x77, 0xfd, 0xdf, 0xd7, 0x8e, 0x75, 0x95,
	0x5a, 0xd4, 0xb2, 0xe0, 0xe1, 0x35, 0xc1, 0xe3, 0x1f, 0x2e, 0x20, 0x03, 0xc6, 0x5b, 0x10, 0xd9,
	0x85, 0xea, 0x79, 0x95, 0x5b, 0x6f, 0x44, 0x74, 0xcd, 0x24, 0x8f, 0x74, 0x4e, 0x4d, 0x62, 0x6d,
	0x2b, 0x3e, 0xf3, 0x52, 0x93, 0x3c, 0xa0, 0x7d, 0xa8, 0x7e, 0x9e, 0x8a, 0x0e, 0x31, 0xe5, 0xc6,
	0x28, 0x01, 0x5d, 0xc4, 0xf8, 0x2d, 0xa0, 0xae, 0x38, 0x6b, 0x9a, 0xa9, 0xe5, 0x72, 0xf3, 0xe6,
	0x7d, 0xb3, 0x63, 0x0d, 0xa2, 0x16, 0x8c, 0xb7, 0xc1, 0x63, 0x45, 0xcf, 0x68, 0x7c, 0x4b, 0xcf,
	0xde, 0xc1, 0x21, 0x55, 0xb0, 0xf8, 0x03, 0x20, 0xd3, 0x8f, 0x5f, 0xc0, 0xaa, 0xb2, 0x43, 0x77,
	0x2a, 0xd9, 0x05, 0xaf, 0xed, 0x1d, 0xa0, 0x53, 0x27, 0x2a, 0x83, 0x5f, 0xc2, 0x9a, 0x01, 0xcc,
	0x58, 0xd7, 0xd9, 0x53, 0x22, 0x6a, 0x9a, 0x26, 0x3a, 0x15, 0xbf, 0x03, 0x6f, 0xef, 0xe0, 0x10,
	0xaf, 0x03, 0x6a, 0x79, 0x37, 0x9f, 0x4a, 0xeb, 0x57, 0x1b, 0xe1, 0x0d, 0xf0, 0x15, 0x5a, 0x69,
	0x67, 0x9a, 0x91, 0x0a, 0xc7, 0x65, 0xbc, 0x03, 0xbe, 0x95, 0xfa, 0x3e, 0x3e, 0xdf, 0x7f, 0xfc,
	0xfd, 0x72, 0xe8, 0xfc, 0xbc, 0x1c, 0x3a, 0xbf, 0x2e, 0x87, 0xce, 0xd7, 0xdf, 0xc3, 0x07, 0x39,
	0xd2, 0xff, 0x81, 0x6f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x75, 0x2e, 0x50, 0x14, 0x05,
	0x00, 0x00,
}
